name: Daily Model Training

on:
  schedule:
    - cron: '0 0 * * *'  # Minuit UTC
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: http://localhost:5000
      MONGO_URI: mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASS }}@localhost:27017/
      DB_NAME: reservation
      COLLECTION_NAME: ListTransitaire
    
    services:
      mlflow:
        image: mlflow/mlflow:latest
        ports:
          - 5000:5000
        env:
          MLFLOW_ARTIFACT_ROOT: ./mlruns
        options: >-
          --health-cmd "curl -f http://localhost:5000 || exit 1"
          --health-interval 10s
          --health-timeout 30s
          --health-retries 5
      
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASS }}
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok'"
          --health-interval 10s
          --health-timeout 30s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-dotenv pymongo mlflow
    
    - name: Create MLflow directory
      run: mkdir -p mlruns
    
    - name: Wait for services
      run: |
        echo "Waiting for MongoDB to be ready..."
        timeout 120 bash -c 'until mongosh --eval "db.runCommand(\"ping\").ok" $MONGO_URI; do sleep 2; done'
        echo "Waiting for MLflow to be ready..."
        timeout 120 bash -c 'until curl -f http://localhost:5000; do sleep 2; done'
    
    - name: Run training
      run: |
        python train_model.py
    
    - name: Upload model artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-$(date +'%Y-%m-%d')
        path: best_model.pkl
        retention-days: 7
