name: Daily Model Training

on:
  schedule:
    - cron: '0 0 * * *'  # Minuit UTC
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: http://localhost:5000
      DB_NAME: reservation
      COLLECTION_NAME: ListTransitaire

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-dotenv pymongo mlflow pymongo[srv]

    - name: Create MLflow directory
      run: mkdir -p mlruns

    - name: Start MLflow server (background)
      run: |
        mlflow server --backend-store-uri sqlite:///mlruns/mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 &
        sleep 5

    - name: Run training
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        python train_model.py
    
    - name: Upload model artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-$(date +'%Y-%m-%d')
        path: best_model.pkl
        retention-days: 7

    - name: Send email notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_SENDER }}  # Votre adresse Gmail complète
        password: ${{ secrets.EMAIL_PASSWORD }}  # Mot de passe d'application généré
        subject: "Workflow ${{ github.workflow }} - ${{ job.status }}"
        html_body: |  # <-- Remplace 'body' et 'content_type'
          <p><strong>Statut</strong>: ${{ job.status }}</p>
          <p><strong>Dépôt</strong>: ${{ github.repository }}</p>
          <p><strong>Lien</strong>: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">Voir le workflow</a></p>
          <p><strong>Date</strong>: $(date -u +"%Y-%m-%d %H:%M:%S UTC")</p>
        to: ${{ secrets.EMAIL_RECIPIENT }}  # Adresse de destination
        from: GitHub Actions
        secure: true  # Important pour Gmail
