name: Daily Model Training

on:
  schedule:
    - cron: '0 0 * * *' # Minuit UTC chaque jour
  workflow_dispatch: # Permet de déclencher manuellement

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    services:
      mlflow:
        image: mlflow/mlflow
        ports:
          - 5000:5000
        options: >-
          --health-cmd "curl -f http://localhost:5000 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install -y libpoppler-cpp-dev
        
    - name: Configure secrets
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
        echo "MLFLOW_TRACKING_URI=http://localhost:5000" >> .env
    
    - name: Train model
      run: |
        source .env
        python ml_pipeline.py \
          --mongo-uri "$MONGO_URI" \
          --db-name "reservation" \
          --collection "ListTransitaire"
    
    - name: Archive model artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: model-artifacts
        path: |
          best_model.pkl
          mlruns/
