name: Daily Model Training

on:
  schedule:
    - cron: '0 0 * * *'  # Minuit UTC
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: http://localhost:5000
      DB_NAME: reservation
      COLLECTION_NAME: ListTransitaire

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-dotenv pymongo mlflow pymongo[srv]

    - name: Create MLflow directory
      run: mkdir -p mlruns

    - name: Start MLflow server (background)
      run: |
        mlflow server --backend-store-uri sqlite:///mlruns/mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 &
        sleep 5  # Attendre que le serveur démarre

    - name: Run training
      env:
        MONGO_URI: mongodb+srv://dghaiesoumaima0:2QM6D3ftO5H6TxH9@cluster0.g1zvwyt.mongodb.net/?retryWrites=true&w=majority
      run: |
        python train_model.py
    
    - name: Upload model artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-$(date +'%Y-%m-%d')
        path: best_model.pkl
        retention-days: 7
