name: Daily Model Training

on:
  schedule:
    - cron: '0 0 * * *'  # Minuit UTC
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  train-model:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: http://localhost:5000
      DB_NAME: reservation
      COLLECTION_NAME: ListTransitaire

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-dotenv pymongo mlflow pymongo[srv]

    - name: Create MLflow directory
      run: mkdir -p mlruns

    - name: Start MLflow server (background)
      run: |
        mlflow server --backend-store-uri sqlite:///mlruns/mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 &
        sleep 5

    - name: Run training
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        # Supprimer l'ancien modèle pour forcer la régénération
        if [ -f "best_model.pkl" ]; then
          rm -f best_model.pkl
          echo "Ancien modèle supprimé"
        fi
        
        # Exécuter l'entraînement avec vérification
        python train_model.py
        
        # Vérifier que le nouveau modèle a été créé
        if [ ! -f "best_model.pkl" ]; then
          echo "ERREUR: best_model.pkl n'a pas été généré"
          exit 1
        fi
        
        # Afficher les infos du fichier pour le debug
        ls -lh best_model.pkl
        stat best_model.pkl
    
    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-${{ github.run_id }}-${{ github.run_number }}
        path: best_model.pkl

    
    - name: Commit and push model updates
      run: |
        # Configurer Git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Créer un répertoire pour les backups s'il n'existe pas
        mkdir -p model_backups
        
        # Copier le modèle dans le répertoire de backups avec un timestamp
        TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
        cp best_model.pkl "model_backups/best_model_${TIMESTAMP}.pkl"
        
        # FORCER le commit même si le contenu est identique
        git add -f best_model.pkl
        git add -f model_backups/*
        
        # Créer un fichier metadata pour forcer un changement
        echo "Last training: ${TIMESTAMP}" > model_metadata.txt
        git add -f model_metadata.txt
        
        # Committer même si Git ne détecte pas de changement
        git commit --allow-empty -m "Force model update - ${TIMESTAMP}"
        
        # Pousser les changements
        git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
        
    - name: Send email notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_SENDER }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Workflow ${{ github.workflow }} - ${{ job.status }}"
        html_body: |
          <p><strong>Statut</strong>: ${{ job.status }}</p>
          <p><strong>Dépôt</strong>: ${{ github.repository }}</p>
          <p><strong>Lien</strong>: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">Voir le workflow</a></p>
        to: ${{ secrets.EMAIL_RECIPIENT }}
        from: GitHub Actions
        secure: true
