name: Daily Model Training

on:
  schedule:
    - cron: '0 0 * * *'  # Minuit UTC
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  train-model:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: http://localhost:5000
      DB_NAME: reservation
      COLLECTION_NAME: ListTransitaire

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-dotenv pymongo mlflow pymongo[srv] scikit-learn

    - name: Create directories
      run: |
        mkdir -p mlruns
        mkdir -p model_backups

    - name: Start MLflow server (background)
      run: |
        mlflow server --backend-store-uri sqlite:///mlruns/mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 &
        sleep 5

    - name: Run training
      run: |
        python train_model.py
    
    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts-${{ github.run_id }}
        path: |
          best_model.pkl
          training.log
          model_backups/

    - name: Commit and push model
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull
        
        # Ajouter uniquement le modèle principal
        if [ -f "best_model.pkl" ]; then
          git add best_model.pkl
          git commit -m "Auto-update model $(date +'%Y-%m-%d')"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        else
          echo "Aucun modèle à committer"
          exit 0
        fi

    - name: Clean up
      run: |
        rm -rf __pycache__/
        rm -rf mlruns/

    - name: Send email notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_SENDER }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Workflow ${{ github.workflow }} - ${{ job.status }}"
        html_body: |
          <p><strong>Statut</strong>: ${{ job.status }}</p>
          <p><strong>Dépôt</strong>: ${{ github.repository }}</p>
          <p><strong>Lien</strong>: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">Voir le workflow</a></p>
        to: ${{ secrets.EMAIL_RECIPIENT }}
        from: GitHub Actions
        secure: true
