name: Daily Model Training

on:
  schedule:
    - cron: '0 0 * * *'  # Minuit UTC
  workflow_dispatch:  # Permet un déclenchement manuel

jobs:
  train-model:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: http://localhost:5000
    
    services:
      mlflow:
        image: mlflow/mlflow
        ports:
          - 5000:5000
      
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASS }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-dotenv
    
    - name: Run training
      env:
        MONGO_URI: mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASS }}@localhost:27017/
        DB_NAME: reservation
        COLLECTION_NAME: ListTransitaire
      run: |
        python train_model.py
    
    - name: Upload model
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: best_model.pkl
        retention-days: 7
